### ISSUE TITLE
[EPIC] Keyserver Migration Plan

### ISSUE THREAD

**Issue by Elyniss** [WalletConnect/keys-server#91]
@Elyniss:

- [ ]  Integration tests with docker-compose
- [x] #92
- [ ]  Research Cloud9 db dump extraction
- [ ]  Try getting MongoDB snapshot

@xav:

- [x] #93
- [x]  Migrate Prod database
- [x]  NLB → ALB
- [x] #113

After issue is complete remember to cleanup repo issues
